name: Deploy Car Rental Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@34.239.113.100 "echo SSH Connection Successful"

      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/id_rsa -r ./* ubuntu@34.239.113.100:/var/www/html/carrental
          ssh -i ~/.ssh/id_rsa ubuntu@34.239.113.100 "sudo systemctl restart apache2"
